server:
  port: 8088
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weapp?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1215
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml